### ISSUE TITLE
Error while installing using pip

### ISSUE THREAD

**Issue by MaciejkaG** [top-gg/python-sdk#36]
This issue tracker is **ONLY** used for reporting bugs with __dblpy__. Feel free to share your suggestions in the #api channel in our [Discord server](https://discord.gg/EYHTgJX)!

For help with general Python issues, use [StackOverflow](https://stackoverflow.com), our [#development channel](https://discord.gg/EYHTgJX), or the [Python Discord server](https://discord.gg/python).

## Expected Behavior
pip should install dblpy

## Current Behavior
pip shows an error `Could not find a version that satisfies the requirement dblpy (from versions: )
No matching distribution found for dblpy`

## Development Environment
I'm on the newest Raspberry Pi OS and I got python 3.7.3.

## Steps to Reproduce
1. Open LXTerminal
2. Type "pip install dblpy"
3. That's it.

## Context
I wanted to install Python library for top.gg to make my bot, check if user voted.

## Detailed Description
Screenshot: ![image](https://user-images.githubusercontent.com/68497547/100870648-44951f00-349f-11eb-8e8f-8e5696212a92.png)

**Comment by DrLarck** [comment]
Hey !

What version of `pip` are you using ?
To check it use 
```
$pip --version
```

I know that on my RasPi I had to use `pip3` instead of `pip`, maybe try to use
```
$pip3 install dblpy
```

**Comment by MaciejkaG** [comment]
> Hey !
> 
> What version of `pip` are you using ?
> To check it use 
> ```
> $pip --version
> ```
> 
> I know that on my RasPi I had to use `pip3` instead of `pip`, maybe try to use
> ```
> $pip3 install dblpy
> ```

Thanks! It helped!
