### ISSUE TITLE
pip dependecy conflicts

### ISSUE THREAD

**Issue by EEKIM10** [top-gg/python-sdk#38]
## Expected Behavior
Installing goes fine, with no dependency conflicts

## Current Behavior
```shell
$ pip install -Ur requirements.txt
...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dblpy 0.3.4 requires aiohttp<3.7.0,>=3.3.0, but you have aiohttp 3.7.3 which is incompatible.
Successfully installed aiofiles-0.6.0 aiohttp-3.7.3 humanize-3.2.0 yarl-1.6.3
...
```

## Development Environment
Python: 3.8.5
Pip: 20.3.3
sdk: 0.3.4

## Steps to Reproduce
Requirements file:
```
humanize>=3.1.0
jishaku>=1.19.0.194
eekues>=0.1.4
aiohttp>=3.7
postbin>=1.0.6
yarl>=1.5.1
aiofiles
```
1. `pip install -Ur requirements.txt` (or --upgrade -r requirements.txt)
2. result

I believe that this could be resolved by specifying a greater than version in your requirements.txt.
For example, 
`aiohttp>=3.6`

**Comment by shivaco** [comment]
The package does not have a strict dependency anymore, meaning this is not an issue in future versions; I will roll out a full update to PyPi soon.
