### ISSUE TITLE
maybe documentation is outdated

### ISSUE THREAD

**Issue by CyberRex0** [top-gg/python-sdk#46]
I saw readthedocs of dblpy.

I saw function "DBLClient.get_bot_votes()", so I tried but it says "get_bot_votes no attribute"

I checked DBLClient instance via dir(), I found alike function "get_bot_upvotes()".

It works, so maybe documentation was outdated or mistypo.

Please check.

**Comment by shivaco** [comment]
No worries, I'm perfectly aware of this and will work on a proper solution after the 1.0 version is fully released.

The documentation itself is updated to 1.0 whereas the stable version currently is 0.4. For now, you'll have to refer to the source code.

**Comment by norinorin** [comment]
The issue has been resolved since topggpy v1 is out. The examples on the pypi page haven't been updated though, you can refer to this repo's [readme](https://github.com/top-gg/python-sdk#examples) and the [docs](https://topggpy.rtfd.io) instead

**Comment by Sitanshu-15** [comment]
The solution is patience
Note: Pretty sure they will update it as soon as 1.1 hits.

**Comment by shivaco** [comment]
Documentation has been officially updated and moved to [topggpy.rtfd.io](https://topggpy.rtfd.io).
