### ISSUE TITLE
Cannot get votes.

### ISSUE THREAD

**Issue by ThatOneCalculator** [top-gg/python-sdk#55]
This issue tracker is **ONLY** used for reporting bugs with __topggpy__. Feel free to share your suggestions in the #api channel in our [Discord server](https://discord.gg/EYHTgJX)!

For help with general Python issues, use [StackOverflow](https://stackoverflow.com), our [#development channel](https://discord.gg/EYHTgJX), or the [Python Discord server](https://discord.gg/python).

## Expected Behavior
`await self.bot.topggpy.get_bot_votes()` should return bot votes.

## Current Behavior
```

Ignoring exception in command votes:
Traceback (most recent call last):
  File "/home/the1calc/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "bot.py", line 122, in votes
    await ctx.send(f"I have {await self.bot.topggpy.get_bot_votes()} votes on top.gg!",
  File "/home/the1calc/.local/lib/python3.8/site-packages/topgg/client.py", line 250, in get_bot_votes
    response = await self.http.get_bot_votes(self.bot_id)
  File "/home/the1calc/.local/lib/python3.8/site-packages/topgg/http.py", line 191, in get_bot_votes
    return await self.request("GET", f"/bots/{bot_id}/votes")
  File "/home/the1calc/.local/lib/python3.8/site-packages/topgg/http.py", line 121, in request
    data = await _json_or_text(resp)
  File "/home/the1calc/.local/lib/python3.8/site-packages/topgg/http.py", line 59, in _json_or_text
    return DataDict(**json.loads(text))
TypeError: type object argument after ** must be a mapping, not list

```

## Development Environment

Module: latest from pip
Python: 3.8.5
OS: Ubuntu Server 20.04.2 LTS

**Comment by ThatOneCalculator** [comment]
Seems #54 fixes this.

**Comment by norinorin** [comment]
Yep. Until it's merged/next release, you can install 9782796b869144b24dc58526f89048ecdfdf1b26 instead. Let me know if you run into other issues.

**Comment by ThatOneCalculator** [comment]
> Yep. Until it's merged/next release, you can install 9782796b869144b24dc58526f89048ecdfdf1b26 instead. Let me know if you run into other issues.

How do I manually install it?

**Comment by norinorin** [comment]
pip install `git+https://github.com/top-gg/python-sdk@9782796b869144b24dc58526f89048ecdfdf1b26#egg=topggpy` or append it to your requirements.txt

**Comment by ThatOneCalculator** [comment]
TYSM, that worked great!

**Comment by ThatOneCalculator** [comment]
@norinorin it appears to be a bit behind; I did `len(votes)`, and it showed 55, but the website shows my bot has 72. Not sure if this is a code problem or an API problem.

**Comment by norinorin** [comment]
The length of the votes doesn't equal the monthly points as it doesn't take weekend bonuses into account.
