### ISSUE TITLE
AttributeError: module 'topgg' has no attribute 'DBLClient'

### ISSUE THREAD

**Issue by QuartzWarrior** [top-gg/python-sdk#58]
This issue tracker is **ONLY** used for reporting bugs with __topggpy__. Feel free to share your suggestions in the #api channel in our [Discord server](https://discord.gg/EYHTgJX)!

For help with general Python issues, use [StackOverflow](https://stackoverflow.com), our [#development channel](https://discord.gg/EYHTgJX), or the [Python Discord server](https://discord.gg/python).

## Expected Behavior
It should say nothing.

## Current Behavior
```
quartz_i_warrior@instance-1:~$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import topgg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quartz_i_warrior/topgg.py", line 8, in <module>
    bot.topggpy = topgg.DBLClient(bot, dbl_token)
AttributeError: module 'topgg' has no attribute 'DBLClient'
>>> 

```
## Development Environment
3.7.3, idk, Debian 10
            |
            |
           \/
`>>> import topgg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quartz_i_warrior/topgg.py", line 8, in <module>
    bot.topggpy = topgg.DBLClient(bot, dbl_token)
AttributeError: module 'topgg' has no attribute 'DBLClient'
>>> topgg.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'topgg' is not defined
>>> import topgg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quartz_i_warrior/topgg.py", line 8, in <module>
    bot.topggpy = topgg.DBLClient(bot, dbl_token)
AttributeError: module 'topgg' has no attribute 'DBLClient'
>>> topgg.version_info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'topgg' is not defined
>>> `
## Steps to Reproduce
1. `python3`
2. `import topgg`
3. `topgg.__version__`
4. `topgg.version_info`

## Context
I am trying to add this into my discord bot to publish current servers but I keep getting the first code clip (error).

**Comment by EEKIM10** [comment]
Cannot repro

```
eek@eek-laptop /t/python-sdk> ls                                                                                                                                                                                                       master
docs  ISSUE_TEMPLATE.md  LICENSE  MANIFEST.in  mypy.ini  PULL_REQUEST_TEMPLATE.md  pytest.ini  README.rst  readthedocs.yml  requirements-dev.txt  requirements-docs.txt  requirements.txt  scripts  setup.py  tests  topgg
eek@eek-laptop /t/python-sdk> git pull                                                                                                                                                                                            
Already up-to-date.
eek@eek-laptop /t/python-sdk> python3                                                                                                                                                                                                 Python 3.9.5 (default, May 19 2021, 11:32:47) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import topgg
>>> topgg.__version__
'1.3.0'
>>> topgg.version_info
VersionInfo(major=1, minor=3, micro=0, releaselevel='final', serial=0)
>>> 
```
I doubt the python version matters here, however, correct me if I am wrong.

Are you installing from source (master branch) or pip?

**Comment by norinorin** [comment]
> File "/home/quartz_i_warrior/topgg.py", line 8, in 

You have actually shadowed the library with your own file. Try changing the filename and retry.

**Comment by QuartzWarrior** [comment]
Oh, I'm dumb thank you so much!
