### ISSUE TITLE
Exeption in auto post loop. Unauthorised (status code: 401)

### ISSUE THREAD

**Issue by Skublik-glek** [top-gg/python-sdk#73]
Exeption in auto post loop

## Expected Behavior
Counting of servers should continue post nubmer of servers and shards

## Current Behavior
After some time auto post stops posting numbers. And I got exeption in console(Exeption in auto post loop; Unauthorised (status code: 401))
![image](https://user-images.githubusercontent.com/82895701/204127487-f279fce8-2412-446a-b361-33b6b8f49dcc.png)

## Development Environment
Python 3.9.0
topggpy 1.4.0
OS Windows Server 2012 R2

## Steps to Reproduce
1. Use topggpy for posting number of servers
2. Use auto post
3. Continue use it for some hours
4. Got exeption 

## Context
Now I should reload my bot to continue post numbers

## Possible Solution
Create new loop if got exeption

## Detailed Description
Constraction used in my cod 
```py
@bot.event
async def on_ready():
    print("Bot is ready")
    bot.loop.create_task(start(bot))

@bot.event
async def on_autopost_success():
    print(
        f"Posted server count ({ggbot.guild_count}), shard count ({bot.shard_count})"
    )
```
![image](https://user-images.githubusercontent.com/82895701/204127487-f279fce8-2412-446a-b361-33b6b8f49dcc.png)

**Comment by shivaco** [comment]
I suspect it's an issue on Top.gg API's side, not topggpy. The library does not modify any data you provide to the objects.

**Comment by Esmeray6** [comment]
Was this resolved in the end?

**Comment by Skublik-glek** [comment]
> Was this resolved in the end?

it was really an issue on Top.gg API's side. I didn't get this exception for year.
